{% set name = "mapraster" %}
{% set version = "2026.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ad5c16a1b3fab65b71767d09776913ba49b77f49dd6b95df88c5343159c07e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - numpy >=1.21,<3
    - xarray >=2023.1,<2026
    - scipy

test:
  imports:
    - mapraster
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/umr-lops/mapraster
  license: MIT
  license_file: LICENSE
  summary: 'Python library to interpolate xarray raster field on image geometry'
  description: |
    mapraster is a Python library to interpolate xarray raster field on image geometry (e.g. line/sample)
  dev_url: https://github.com/umr-lops/mapraster

extra:
  recipe-maintainers:
    - vincelhx
